name: Test Markdown
on:
  push:
    branches:
      - test-markdown
  pull_request:
    paths:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CLI_CONFIG_DIR: ".github"

jobs:
  markdownlint:
    name: Lint by markdownlint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install markdownlint
        run: sudo npm install -g markdownlint-cli
      - name: Display markdownlint
        run: markdownlint --version
      - name: Run markdownlint
        run: markdownlint --dot --config "${CLI_CONFIG_DIR}"/.markdownlint.yml '**/*.md'

  prettier:
    name: Format by prettier
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install prettier
        run: sudo npm install -g prettier
      - name: Display prettier
        run: prettier --version
      - name: Run prettier
        run: prettier --check --parser=markdown '**/*.md'
